### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by cpllbstr** [kishwarshafin/pepper#100]
```09-13-2021 07:52:11] THREAD 0 FINISHED SUCCESSFULLY.
[09-13-2021 07:54:43] FINISHED IMAGE GENERATION
[09-13-2021 07:54:43] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 18 Min 2 Sec
[09-13-2021 07:54:43] STEP 2: RUNNING INFERENCE
[09-13-2021 07:54:43] INFO: PREDICTION OUTPUT: /mnt/raid0/polishing/output//pepper_snp/predictions_09132021_073631/
[09-13-2021 07:54:43] INFO: TOTAL GPU AVAILABLE: 1
[09-13-2021 07:54:43] INFO: AVAILABLE GPU DEVICES: [0]
[09-13-2021 07:54:43] INFO: TOTAL CALLERS: 4
[09-13-2021 07:54:43] INFO: TOTAL THREADS PER CALLER: 25
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 445, in main
    set_profile)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/CallVariant.py", line 116, in call_variant
    threads)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 154, in run_inference
    device_ids)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 87, in polish_genome_distribu
ted_gpu
    predict_distributed_gpu(image_dir, file_chunks, output_dir, model_path, batch_size, total_callers, threads_per_caller, de
vice_ids, num_workers)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 143, in pre
dict_distributed_gpu
    join=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 121, in set
up
    predict(filepath, all_input_files[rank],  output_filepath, model_path, batch_size, num_workers, threads_per_caller, devic
e_ids[rank], rank)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 66, in pred
ict
    output_base, hidden = transducer_model(image_chunk, hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/simple_model.py", line 30, in forward
    x_out, hidden_out = self.gru_encoder(x, hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 716, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED.
```

I have tried to run docker v0.5, as it was metioned in issue #71,  but it doesn't support polishing yet. How can i solve this  problem?

```
+-------------------------------+----------------------+----------------------+
|   3  A100-SXM4-40GB      On   | 00000000:4E:00.0 Off |                    0 |
| N/A   21C    P0    50W / 400W |      3MiB / 40537MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```
I am runnig on A100 GPU.

**Comment by kishwarshafin** [comment]
@cpllbstr , do you see the same error if running on CPU?

**Comment by kishwarshafin** [comment]
@cpllbstr , 

I'll close this issue for now, PEPPER v4 can't support the newest CUDNN, I am hoping the following releases will have this issue fixed as we bring back polishing. Until then, please use the CPU version. Sorry for the inconvenience.
