### ISSUE TITLE
docker GPU version  with cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by masen1991** [kishwarshafin/pepper#71]
Hi @kishwarshafin ,
i also meet the same bug in https://github.com/kishwarshafin/pepper/issues/32
i try re-install CUDA 11.2  toolkit as https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker_gpu/ONT_variant_calling_gpu.md
.
i use this command :
docker run --rm  --ipc=host --gpus 1 -v ${INPUT_DIR}:/home/out/ -v ${OUTPUT_DIR}:/home/local  pepper_deepvariant:r0.4  run_pepper_margin_deepvariant call_variant -b /home/local/test/test/chr22.bam -f /home/local/ref_b38_nanopore/Homo_sapiens_assembly38.fasta -o /home/out/test -p test -s test -t 8 --gvcf --phased_output -g --ont
this is log file :
[1_pepper_snp.log](https://github.com/kishwarshafin/pepper/files/6610169/1_pepper_snp.log)
and this is system nvidia-smi and docker images nvidia-smi 
<img width="658" alt="Screen Shot 2021-06-07 at 11 17 13 PM" src="https://user-images.githubusercontent.com/55567673/121043789-881e6c00-c7e7-11eb-9535-1dce55248f09.png">
<img width="569" alt="Screen Shot 2021-06-07 at 11 19 59 PM" src="https://user-images.githubusercontent.com/55567673/121043796-894f9900-c7e7-11eb-9c0f-e2476340c22e.png">

system info :
cat /proc/version
Linux version 5.4.0-74-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021

uname -a
Linux sl12 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

docker --version
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2

nvidia-docker version
NVIDIA Docker: 2.6.0
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.2-0ubuntu1~20.04.2
 Built:             Tue Mar 30 21:24:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.2-0ubuntu1~20.04.2
  Built:            Mon Mar 29 19:10:09 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.3
  GitCommit:
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

Do you have any ideas about this?

**Comment by kishwarshafin** [comment]
@masen0407  can you change `--gpus 1` to `--gpus all` and let me know if that works?

**Comment by masen1991** [comment]
@kishwarshafin  it is the same error.
[1_pepper_snp.log](https://github.com/kishwarshafin/pepper/files/6612914/1_pepper_snp.log)

**Comment by kishwarshafin** [comment]
@masen0407 , 

Do you have any issue running this on the CPU? I think there's a CUDNN version mismatch happening here. You can also see it here: https://github.com/NVIDIA/tacotron2/issues/109. The docker you are using uses older pytorch which maybe causing this.

**Comment by masen1991** [comment]
@kishwarshafin the cpu version is fine and i get the right results.
but how can i solve this error ?
do u suggest i need to re-install docker?as u can see ,i use docker Version: 20.10.2 and NVIDIA Docker: 2.6.0.and i use the docker images pepper_deepvariant:r0.4 ( sudo docker pull kishwars/pepper_deepvariant:r0.4).
i don't install pytorch  in pc.maybe  do i need to install pytorch on my pc?

**Comment by masen1991** [comment]
@kishwarshafin 
do you have any suggestion？

**Comment by kishwarshafin** [comment]
@masen0407 ,

I can't re-generate this error internally. I tried it on our local cluster and on GCP, however, it seems to run smoothly. Can you try using `test-v0.5` docker to see if that works?

**Comment by masen1991** [comment]
i try test-v0.5 but it still the same .
maybe it only happen some times .
i will close this .

**Comment by masen1991** [comment]
Hi @kishwarshafin :
i try use Version 0.5 update, it still get RuntimeError,but a new log info like this :

NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
So may be this bug can be cause by pytorch version with  RTX 3090 GPUs?

**Comment by kishwarshafin** [comment]
@masen0407 , can you please provide the `r0.5` command that you are running?

**Comment by masen1991** [comment]
> @masen0407 , can you please provide the `r0.5` command that you are running?

sudo docker run --ipc=host \
--gpus all \
-v "${INPUT_DIR}":"${INPUT_DIR}" \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
kishwars/pepper_deepvariant:r0.5-gpu \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${BAM}" \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-p "${OUTPUT_PREFIX}" \
-t ${THREADS} \
-g \
--ont
Same as you provide and replace bam ref as my samples

**Comment by kishwarshafin** [comment]
can you please provide the output of this:
```
sudo docker run --ipc=host \
--gpus all \
-v "${INPUT_DIR}":"${INPUT_DIR}" \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
kishwars/pepper_deepvariant:r0.5-gpu \
pepper_hp torch_stat
```

**Comment by masen1991** [comment]
> can you please provide the output of this:
> 
> ```
> sudo docker run --ipc=host \
> --gpus all \
> -v "${INPUT_DIR}":"${INPUT_DIR}" \
> -v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
> kishwars/pepper_deepvariant:r0.5-gpu \
> pepper_hp torch_stat
> ```

[1.txt](https://github.com/kishwarshafin/pepper/files/7071909/1.txt)

**Comment by kishwarshafin** [comment]
@masen0407 , thank you, I have pushed a new docker image `kishwars/pepper_deepvariant:r0.5-gpu-cu11` which should have `sm_70, sm_80` support for the 30XX RTX cards. Can you please try running:
```
sudo docker run --ipc=host \
--gpus all \
-v "${INPUT_DIR}":"${INPUT_DIR}" \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
kishwars/pepper_deepvariant:r0.5-gpu-cu11 \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${BAM}"  \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-p "${OUTPUT_PREFIX}" \
-t ${THREADS} \
-g \
--ont
```
And let me know if it worked?

**Comment by masen1991** [comment]
> @masen0407 , thank you, I have pushed a new docker image `kishwars/pepper_deepvariant:r0.5-gpu-cu11` which should have `sm_70, sm_80` support for the 30XX RTX cards. Can you please try running:
> 
> ```
> sudo docker run --ipc=host \
> --gpus all \
> -v "${INPUT_DIR}":"${INPUT_DIR}" \
> -v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
> kishwars/pepper_deepvariant:r0.5-gpu-cu11 \
> run_pepper_margin_deepvariant call_variant \
> -b "${INPUT_DIR}/${BAM}"  \
> -f "${INPUT_DIR}/${REF}" \
> -o "${OUTPUT_DIR}" \
> -p "${OUTPUT_PREFIX}" \
> -t ${THREADS} \
> -g \
> --ont
> ```
> 
> And let me know if it worked?

It go well on the pepper and margin_haplotag part ,but when it run on DeepVariant part ,after make_examples, it can not start call_variants  step.
error like this :
2021-08-30 04:06:53.845468: E tensorflow/core/common_runtime/session.cc:91] Failed to create session: Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid
2021-08-30 04:06:53.845491: E tensorflow/c/c_api.cc:2184] Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid

So it go well with pepper but get wrong on deepvariant part now.
[1_pepper.log](https://github.com/kishwarshafin/pepper/files/7074394/1_pepper.log)
[2_margin_haplotag.log](https://github.com/kishwarshafin/pepper/files/7074396/2_margin_haplotag.log)
[4_DeepVariant.log](https://github.com/kishwarshafin/pepper/files/7074397/4_DeepVariant.log)

**Comment by kishwarshafin** [comment]
@masen0407 thank you for bearing with me on this. I have pushed a cuda 11.3 version which should solve this issue.

Can you please run:
```
sudo docker run --ipc=host \
--gpus all \
-v "${INPUT_DIR}":"${INPUT_DIR}" \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
kishwars/pepper_deepvariant:r0.5-gpu-cu113 \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${BAM}"  \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-p "${OUTPUT_PREFIX}" \
-t ${THREADS} \
-g \
--ont
```

**Comment by masen0407** [comment]
@kishwarshafin 
 It all go well now ! 
so i hope you can make a singularity version of this and can use GPUs.
Thanks .

**Comment by masen1991** [comment]
> @masen0407 thank you for bearing with me on this. I have pushed a cuda 11.3 version which should solve this issue.
> 
> Can you please run:
> 
> ```
> sudo docker run --ipc=host \
> --gpus all \
> -v "${INPUT_DIR}":"${INPUT_DIR}" \
> -v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
> kishwars/pepper_deepvariant:r0.5-gpu-cu113 \
> run_pepper_margin_deepvariant call_variant \
> -b "${INPUT_DIR}/${BAM}"  \
> -f "${INPUT_DIR}/${REF}" \
> -o "${OUTPUT_DIR}" \
> -p "${OUTPUT_PREFIX}" \
> -t ${THREADS} \
> -g \
> --ont
> ```

It work on  file such as chr20 or chr1. but when i run on a whole sample bam file, on pepper_variant call_variant  part , it will go wrong like this :
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
like  this :
https://github.com/kishwarshafin/pepper/issues/91
so now the gpu may be all right but with others?

[log.txt](https://github.com/kishwarshafin/pepper/files/7082515/log.txt)

**Comment by kishwarshafin** [comment]
@masen0407 , yes, the GPU issue is fixed, I'll try to see what's happening with the other bug. Are you not using GRCh38 or GRCh37?

**Comment by masen1991** [comment]
> @masen0407 , yes, the GPU issue is fixed, I'll try to see what's happening with the other bug. Are you not using GRCh38 or GRCh37?

I use GRCh38_no_alt_plus_hs38d1_analysis_set.
You may see on this web:
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/
And i also try to use only cpu version ( kishwars/pepper_deepvariant:r0.5-gpu-cu113 but remove -g) ,it also get the same error.
My pc have 126GB mem and 16 cpus.and i can use kishwars/pepper_deepvariant:r0.4 cpu version on the same samples.

So this error may be cause by some other reason.but finally the GPU part is over .thank you again

**Comment by kishwarshafin** [comment]
@masen0407 ,

You are running out of memory. Can you try with a machine with more memory?

**Comment by masen1991** [comment]
@kishwarshafin 
So you mean this version kishwars/pepper_deepvariant:r0.5-gpu-cu113 need more memory than r0.4?
Sorry i can only work on this conputer and the mem can not add more.
maybe can u solve the same bug on r0.4 version cause by not support for the 30XX RTX cards?And i will try to use  r0.4 GPUs to see may be it can work ? memory can not be change because some other reason
If all this can not be done,then i can only use  r0.4 cpu version to work on ONT bam .

**Comment by kishwarshafin** [comment]
@masen0407 ,

Can you try with `-t 8` with v0.5? The newer version does require more memory than the previous one.

**Comment by masen1991** [comment]
@kishwarshafin 
i already try -t 8 once and it still not work.i will try -t 6 or -t 4 and see what will happen

**Comment by masen1991** [comment]
@kishwarshafin t2 and t4 have the same error
BTW，will u consider to solver the same gpu error in r0.4？because maybe pb hifi samples need to use r0.4

**Comment by kishwarshafin** [comment]
@masen0407 , I have fixed the other issue #91 and updated the docker `r0.5-gpu` to support sm_86 and have the latest PEPPER which has that issue fixed. Can you please run:
```
docker pull kishwars/pepper_deepvariant:r0.5-gpu
```
And then confirm that you have updated PEPPER:
```
time docker run -it -v /data:/data --gpus all \
kishwars/pepper_deepvariant:r0.5-gpu \
pepper_variant --version

PEPPER VERSION:  0.5.2
```
And then run your analysis again to see if it fails?

**Comment by masen1991** [comment]
@kishwarshafin 
 It is very weird that i meet error like this
[test_log.txt](https://github.com/kishwarshafin/pepper/files/7106222/test_log.txt)
 log:

mv: cannot stat '/data1/masen/TGS_nanopore/D1803011-TH/pepper/PEPPER_VARIANT_OUTPUT_PHASING.vcf': No such file or directory

And i see this PEPPER VERSION:  0.5.2 use all my 126g mem to run pepper_variant step and the pepper  file nearly 800G size.
so do mem insufficient make this error happen?

**Comment by kishwarshafin** [comment]
@masen0407 , can you please follow the following case-study and see if you can generate the final table? Also, this is not a GPU issue anymore, would be nice if you could close this issue and open a new one with relevant details.

https://github.com/kishwarshafin/pepper/blob/r0.5/docs/pipeline_docker_gpu/ONT_variant_calling_gpu.md
